# Copyright (c) 2024 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- job:
    name: ovs-exporter-build-container-image
    parent: ci-build-container-image
    vars: &container_image_vars
      promote_container_image_job: ovs-exporter-upload-container-image
      container_images:
        - context: .
          registry: registry.atmosphere.dev
          repository: registry.atmosphere.dev/library/ovs-exporter
          arch:
            - linux/amd64
            - linux/arm64
          tags:
            - "{{ zuul.commit_id }}"
            - "{{ zuul.tag is defined | ternary(zuul.tag, 'latest') }}"

- job:
    name: ovs-exporter-upload-container-image
    parent: ci-upload-container-image
    vars: *container_image_vars

- job:
    name: ovs-exporter-promote-container-image
    parent: ci-promote-container-image
    vars: *container_image_vars

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - ovs-exporter-build-container-image
    gate:
      jobs:
        - ovs-exporter-upload-container-image
    promote:
      jobs:
        - ovs-exporter-promote-container-image
